### ISSUE TITLE
Quickstarts OSS site , Repo and App Catalog clean up task list

### ISSUE THREAD

**Issue by jpvajda** [newrelic/opensource-website#833]
Say good bye to old quickstarts and hello to new quickstarts.... 

![spidey](https://user-images.githubusercontent.com/1395158/132773972-ce62c5b4-e0d6-4fe7-b502-9e56e1df01c2.jpg)

### Acceptance criteria 

- [x] Wait for repo name change before doing this work https://github.com/newrelic/newrelic-observability-packs/issues/228
- [x] Follow [these instructions](https://github.com/newrelic/opensource-website/wiki/Contributing-Project-Data) to add this project to the OSS Site and remove the [old quickstarts project](https://opensource.newrelic.com/projects/newrelic/nr1-quickstarts) from the site
- [x] Check the usage of the quickstarts app following [this process](https://github.com/newrelic/nr1-catalog/wiki/New-Relic-One-App-Catalog-How-To-Guide#1-conduct-a-litmus-test-for-an-applications-health) to decide if we can just remove it or if we need to notify users of the app.
- [x] commit by using `feat` or `fix` so we can bump the version on the OSS site. 🏗️ 
- [x] update application and readme to point users to I/O both internally and externally
- [x] deploy a new version of Nr1 Quickstarts

**Comment by rudouglas** [comment]
Also for review:

 - Archive `nr1-quickstarts` https://github.com/newrelic/nr1-quickstarts/pull/58

**Comment by jpvajda** [comment]
can you fix )` Issues at the project owner's discertion`

https://opensource.newrelic.com/oss-category/

**Comment by rudouglas** [comment]
Fixed that @jpvajda, do you think usage is low enough to warrant not reaching out to users?

**Comment by jpvajda** [comment]
@rudouglas oh let me check the statz...

**Comment by jpvajda** [comment]
@rudouglas here's what we need to do to account for the higher usage of this application.

1. update the readme to specify this project will officially be archived on Nov 1st and all users of quickstarts should visit the I/O external site for more details on what we are changing to . With this being said, let's leave the repo set to nr1 catalog until Nov 1st. I'll create a follow up ticket to archive the repo and remove the app from the catalog on nov 1.

2. Update the application to point users to the internal I/O experience. include the following to point users to the right place.

<img width="1429" alt="Screen Shot 2021-09-27 at 12 26 33 PM" src="https://user-images.githubusercontent.com/1395158/134966544-df09480d-a476-4c5a-aa85-362b613124eb.png">

**Comment by rudouglas** [comment]
Sweety here is the updated application shots

<img width="1431" alt="Screenshot 2021-09-28 at 13 31 20" src="https://user-images.githubusercontent.com/17122543/135087322-20d18e1a-b239-44b3-a212-56c6f5d5589e.png">
<img width="1471" alt="Screenshot 2021-09-28 at 13 31 29" src="https://user-images.githubusercontent.com/17122543/135087418-06f3ccbb-06c7-4a80-be4a-5dfa1aa16835.png">

**Comment by rudouglas** [comment]
And the PR https://github.com/newrelic/nr1-quickstarts/pull/59

**Comment by rudouglas** [comment]
Waiting for this to be pushed to Staging and EU

**Comment by rudouglas** [comment]
Waiting on the push to Staging and Production
